#include monitoring, log

name: payment-frontend

server:
  port: 80

payment-backend:
  host: ${deploy::payment-backend@ingress.host}
  path: ${payment-backend@server.context}
  timeoutMs: #{3 * 60 * 1000}